version: '3.8'

services:
  cart:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    restart: always

  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    restart: always

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    restart: always

  service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: service-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: always
