apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
data:
  PORT: "3003"
  MONGODB_URI: "mongodb+srv://cart:cart@cluster0.1mpslgs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "8yNHXbwASKGf8o+kzn99fE0qbnQbF1lmwq0HBzsYUYQ="