apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-frontend
  template:
    metadata:
      labels:
        app: e-commerce-frontend
    spec:
      containers:
        - name: e-commerce-frontend
          image: sainathislavath/e-commerce-frontend
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config