apiVersion: v1
kind: Service
metadata:
  name: e-commerce-frontend
spec:
  type: LoadBalancer # NodePort in local
  selector:
    app: e-commerce-frontend
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30000