apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "3004"
  MONGODB_URI: "mongodb+srv://orders:orders@cluster0.3pucrvp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "8yNHXbwASKGf8o+kzn99fE0qbnQbF1lmwq0HBzsYUYQ="