apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  PORT: "3002"
  MONGODB_URI: "mongodb+srv://products:products@cluster0.rtqnl8v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "8yNHXbwASKGf8o+kzn99fE0qbnQbF1lmwq0HBzsYUYQ="