apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "3001"
  MONGODB_URI: "mongodb+srv://users:users@cluster0.sfczztj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "8yNHXbwASKGf8o+kzn99fE0qbnQbF1lmwq0HBzsYUYQ="